// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbxombgwzqqumubpaogo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFieG9tYmd3enFxdW11YnBhb2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NTg0MzgsImV4cCI6MjA5MjMzNDQzOH0.afC1Yq5HtoTbji7sQeAc3m4S_zKTzbEyGCSlp9bE8B8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});